name:                aoc2015
version:             0.1.0.0
github:              "flo80/aoc2015"
license:             BSD3
author:              "Florian Lloyd-Pötscher"
maintainer:          "flo@poetscher.org"
copyright:           "2019 Florian Lloyd-Pötscher"

#extra-source-files:

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Advent of Code 2015

dependencies:
- base >= 4.7 && < 5
- containers
- linear
- split
- HUnit
- bytestring
- base16-bytestring
- utf8-string
- cryptohash-md5
- memoize 

library:
  source-dirs: src

executables:
  aoc2015-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2015

tests:
  aoc2015-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2015
